<!-- Generated by graphviz version 2.26.3 (20100126.1600)
 --><!-- Title: mygraph Pages: 1 --><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="62pt" height="120pt" viewBox="0.00 0.00 62.00 120.00">
<g id="graph1" class="graph" transform="scale(1 1) rotate(0) translate(4 116)">
<title>mygraph</title>
<polygon fill="white" stroke="white" points="-4,5 -4,-116 59,-116 59,5 -4,5"/>
<!-- p -->
<g id="node1" class="node"><title>p</title>
<ellipse fill="none" stroke="black" cx="27" cy="-93" rx="27" ry="19.0919"/>
<text text-anchor="middle" x="27" y="-89.9" font-family="Times Roman,serif" font-size="14.00">p</text>
</g>
<!-- q -->
<g id="node3" class="node"><title>q</title>
<ellipse fill="none" stroke="black" cx="27" cy="-19" rx="27" ry="19.0919"/>
<text text-anchor="middle" x="27" y="-15.9" font-family="Times Roman,serif" font-size="14.00">q</text>
</g>
<!-- p&#45;&gt;q -->
<g id="edge2" class="edge"><title>p-&gt;q</title>
<path fill="none" stroke="black" d="M27,-73.9432C27,-66.1493 27,-56.9538 27,-48.3381"/>
<polygon fill="black" stroke="black" points="30.5001,-48.2494 27,-38.2495 23.5001,-48.2495 30.5001,-48.2494"/>
</g>
</g>
</svg>